CREATE DATABASE IF NOT EXISTS ds_crud;
USE ds_crud;

CREATE TABLE IF NOT EXISTS clientes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  endereco VARCHAR(100),
  telefone VARCHAR(20),
  data_nascimento DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);